# Generated by Django 5.2.7 on 2025-12-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandHomeAppliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAppliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=200, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='HomeAppliances.brandhomeappliances')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAppliancesKeyspecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('homeappliances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyspecs', to='HomeAppliances.homeappliances')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAppliancesOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('homeappliances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='HomeAppliances.homeappliances')),
            ],
        ),
    ]
