from .populate_laptop_brand import Command as PopulateLaptopbrandCommand
from .populate_laptop_laptops import Command as PoulateLaptoplaptopsCommand
from .populate_laptop_overviews import Command as PoulateLaptopoverviewsCommand
from .populate_laptop_keyspecs import Command as PoulateLaptopkeyspecsCommand
