# Generated by Django 5.2.7 on 2025-12-12 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=200, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='laptops.brandlaptop')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopKeyspecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyspecs', to='laptops.laptop')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='laptops.laptop')),
            ],
        ),
    ]
